### ISSUE TITLE
[BUG] Revalidation error

### ISSUE THREAD

**Issue by barpec12** [Backdoorek/Librus-Tricks#13]
```
Traceback (most recent call last):
  File "/home/barpec12/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/barpec12/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/barpec12/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/barpec12/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/barpec12/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/barpec12/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "mojbot.py", line 59, in receive_message
    newslist = session.news_feed()
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 359, in news_feed
    return self.return_objects('SchoolNotices', cls=SynergiaNews, extraction_key='SchoolNotices')
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 212, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 163, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 113, in get
    response = self.dispatch_http_code(response, callback=self.get, callback_args=path, callback_kwargs=request_params)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 80, in dispatch_http_code
    self.user.revalidate_user()
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/auth.py", line 63, in revalidate_user
    self.token = new_token.json()['accessToken']
KeyError: 'accessToken'

```

**Comment by Backdoorek** [comment]
która wersja `librus-tricks`?

**Comment by barpec12** [comment]
0.7.4rc2

**Comment by Backdoorek** [comment]
Hmm, **_u mnie działa_** (od 36h działa worker, który czeka na to, żeby dostać 401 i zrobić revalidację), może znowu coś librus zwalił. Zacznę focusować kolejne wersję na lepszy error tracing. Póki nie wyjaśni się czym to jest spowodowane to nie zamykam issue

**Comment by Backdoorek** [comment]
*Próbował pan wyłączyć i włączyć?*

**Comment by barpec12** [comment]
Tak XD. Po ponownym uruchomieniu jest ok, ale ten problem pojawia się po jakimś czasie

**Comment by Backdoorek** [comment]
Pewnie +- co 24h

**Comment by Backdoorek** [comment]
Więc, miło by było jakbyś na początku swoich skryptów dodał te dwie linijki
```python
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(module)s:%(lineno)d - %(funcName)s - %(message)s')
```
W wersji `0.7.4` (Już nie będzie więcej rc) dodałem trochę loggerów więc wszelkiego rodzaju dziwne błedy z auth będą łatwiejsze do debug'u

**Comment by mimi89999** [comment]
Mam ten sam problem w https://github.com/mimi89999/Botek-Librus. Czasami wyrzuca błąd, ale przy ponownym uruchomieniu działa dobrze.

```
Traceback (most recent call last):
  File "LibrusOgloszenia.py", line 63, in <module>
    announcements = Announcements(Librus(config.login, config.password), on_new_announcement, config.filter_class)
  File "/home/scripts/Botek-Librus/librus.py", line 31, in __init__
    self.login()
  File "/home/scripts/Botek-Librus/librus.py", line 80, in login
    'accounts'][0]['accessToken']
KeyError: 'accounts'
```

**Comment by Backdoorek** [comment]
Widząc ten `KeyError` spodziewałbym się, że nie ma zawartych kont w odpowiedzi librusa

**Comment by mimi89999** [comment]
Jak w zeszłym roku robiłem MITM na aplikacji Librusa, to ona dokładnie tak odświerzała swój token. Wątpię aby coś zmieniali, bo za drugim razem działa. Może jakiś bug u nich?

**Comment by Backdoorek** [comment]
Uruchomiłem w piątek skrypt, który odpytywał librusa co 15 minut i czekał na 401 z jego strony. Udało mu się odświeżyć token 3 razy i za 4 razem też dostałem `KeyError`

```python
2019-09-29 11:09:32,651:INFO:root:Checking is user's token is valid
2019-09-29 11:09:32,654:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.librus.pl:443
2019-09-29 11:09:32,787:DEBUG:urllib3.connectionpool:https://api.librus.pl:443 "GET /2.0/Me HTTP/1.1" 401 None
2019-09-29 11:09:32,790:DEBUG:root:False
2019-09-29 11:09:32,790:INFO:root:Token is not valid
2019-09-29 11:09:32,790:INFO:root:Trying to query for grades
2019-09-29 11:09:32,794:DEBUG:urllib3.connectionpool:Resetting dropped connection: api.librus.pl
2019-09-29 11:09:32,928:DEBUG:urllib3.connectionpool:https://api.librus.pl:443 "GET /2.0/Subjects HTTP/1.1" 401 None
2019-09-29 11:09:32,931:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): portal.librus.pl:443
2019-09-29 11:09:33,140:DEBUG:urllib3.connectionpool:https://portal.librus.pl:443 "GET /api/v2/SynergiaAccounts/fresh/6379114u HTTP/1.1" 401 None
2019-09-29 11:09:33,142:ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "poller.py", line 35, in <module>
    logging.debug(session.grades_categorized)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 243, in grades_categorized
    for subject in self.subjects():
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 368, in subjects
    return self.return_objects('Subjects', cls=SynergiaSubject, extraction_key='Subjects')
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 212, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 163, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 113, in get
    response = self.dispatch_http_code(response, callback=self.get, callback_args=path, callback_kwargs=request_params)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 80, in dispatch_http_code
    self.user.revalidate_user()
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/auth.py", line 63, in revalidate_user
    self.token = new_token.json()['accessToken']
KeyError: 'accessToken'
```

**Comment by Backdoorek** [comment]
@mimi89999 zrobiłeś już update do `0.7.4`?

**Comment by mimi89999** [comment]
Update czego? Botek-Librus ma własną implementację Librusa, bo wtedy jeszcze nie było tego repo. Z tego korzystam tylko w środowisku dev forku LibrekBot, ale tam mam mastera, żeby móc się zalogować. 🙂

Błędy mam tylko z logów Botek-Librus.

**Comment by Backdoorek** [comment]
Oh ok

**Comment by Backdoorek** [comment]
Oh yeah, wreszcie wiemy co serwer zwraca

```
2019-10-01 11:12:14,190:DEBUG:root:Checking token...
2019-10-01 11:12:14,190:DEBUG:root:Dispatching code
2019-10-01 11:12:14,195:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,197:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,198:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,199:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,200:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,201:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,202:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,203:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,204:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,206:DEBUG:root:Looking for response in cache...
2019-10-01 11:12:14,206:DEBUG:root:{'Fizyka': [<SynergiaGrade 5 from SynergiaSubject with id 37660 added 2019-09-17 10:05:41>, <SynergiaGrade 5 from SynergiaSubject with id 37660 added 2019-09-19 11:42:34>], 'Informatyka': [<SynergiaGrade 2+ from SynergiaSubject with id 37664 added 2019-09-11 11:38:11>], 'Język niemiecki': [<SynergiaGrade - from SynergiaSubject with id 37667 added 2019-09-15 13:34:27>], 'Język polski': [<SynergiaGrade 1 from SynergiaSubject with id 37668 added 2019-09-30 11:24:28>, <SynergiaGrade 4- from SynergiaSubject with id 37668 added 2019-10-01 09:38:11>], 'Matematyka': [<SynergiaGrade + from SynergiaSubject with id 37670 added 2019-09-04 08:47:47>, <SynergiaGrade np from SynergiaSubject with id 37670 added 2019-09-12 08:16:39>, <SynergiaGrade + from SynergiaSubject with id 37670 added 2019-09-17 13:33:31>], 'Wychowanie fizyczne': [<SynergiaGrade 5 from SynergiaSubject with id 37678 added 2019-09-20 11:33:49>]}
2019-10-01 11:17:14,288:INFO:root:Checking is user's token is valid
2019-10-01 11:17:14,290:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.librus.pl:443
2019-10-01 11:17:14,457:DEBUG:urllib3.connectionpool:https://api.librus.pl:443 "GET /2.0/Me HTTP/1.1" 401 None
2019-10-01 11:17:14,460:DEBUG:root:False
2019-10-01 11:17:14,461:INFO:root:Token is not valid
2019-10-01 11:17:14,461:INFO:root:Trying to query for grades
2019-10-01 11:17:14,461:DEBUG:root:Looking for response in cache...
2019-10-01 11:17:14,464:DEBUG:root:Cache is outdated!
2019-10-01 11:17:14,466:DEBUG:urllib3.connectionpool:Resetting dropped connection: api.librus.pl
2019-10-01 11:17:14,599:DEBUG:urllib3.connectionpool:https://api.librus.pl:443 "GET /2.0/Subjects HTTP/1.1" 401 None
2019-10-01 11:17:14,599:DEBUG:root:Checking token...
2019-10-01 11:17:14,600:DEBUG:root:Token is expired, revalidation!
2019-10-01 11:17:14,600:DEBUG:root:Creating new temporary request session
2019-10-01 11:17:14,602:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): portal.librus.pl:443
2019-10-01 11:17:14,795:DEBUG:urllib3.connectionpool:https://portal.librus.pl:443 "GET /api/v2/SynergiaAccounts/fresh/6379114u HTTP/1.1" 401 None
2019-10-01 11:17:14,797:DEBUG:root:HTTP payload is {'error': 'access_denied', 'message': 'The resource owner or authorization server denied the request.', 'hint': 'Access token is invalid'}
2019-10-01 11:17:14,798:ERROR:root:Uncaught exception
Traceback (most recent call last):
  File "poller.py", line 35, in <module>
    logging.debug(session.grades_categorized)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 255, in grades_categorized
    for subject in self.subjects():
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 380, in subjects
    return self.return_objects('Subjects', cls=SynergiaSubject, extraction_key='Subjects')
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 224, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 172, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 119, in get
    response = self.dispatch_http_code(response, callback=self.get, callback_args=path, callback_kwargs=request_params)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 84, in dispatch_http_code
    self.user.revalidate_user()
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/auth.py", line 69, in revalidate_user
    self.token = new_token.json()['accessToken']
KeyError: 'accessToken'
```

**Comment by mimi89999** [comment]
Hmm... Czyli w takim wypadku trzeba odświeżyć token z Portalu?

**Comment by Backdoorek** [comment]
Well... mam od tego `session.user.revalidate_root()`

**Comment by Backdoorek** [comment]
Jak wrócę do domu to postaram się jakoś to zaimplementować

**Comment by Backdoorek** [comment]
```
pip install git+https://github.com/Backdoorek/Librus-Tricks.git@0.7.5-rc.1
```

**Comment by barpec12** [comment]
Ja przetestuję

**Comment by Backdoorek** [comment]
Pospieszyłem się z `0.7.5`
```
2019-10-02 11:54:57,651 - DEBUG - connectionpool:815 - _new_conn - Starting new HTTPS connection (1): api.librus.pl:443
2019-10-02 11:54:57,816 - DEBUG - connectionpool:396 - _make_request - https://api.librus.pl:443 "GET /2.0/Me HTTP/1.1" 401 None
2019-10-02 11:54:57,818 - DEBUG - poller:24 - <module> - Is token valid: False
2019-10-02 11:54:57,822 - DEBUG - core:176 - get_cached_response - Response is too old! Trying to get latest response from api
2019-10-02 11:54:57,823 - DEBUG - connectionpool:241 - _get_conn - Resetting dropped connection: api.librus.pl
2019-10-02 11:54:57,957 - DEBUG - connectionpool:396 - _make_request - https://api.librus.pl:443 "GET /2.0/Subjects HTTP/1.1" 401 None
2019-10-02 11:54:57,958 - DEBUG - core:84 - dispatch_http_code - Dispatching response status
2019-10-02 11:54:57,958 - INFO - core:86 - dispatch_http_code - Server returned error code "TokenIsExpired", trying to obtain new token
2019-10-02 11:54:57,959 - DEBUG - connectionpool:815 - _new_conn - Starting new HTTPS connection (1): portal.librus.pl:443
2019-10-02 11:54:58,239 - DEBUG - connectionpool:396 - _make_request - https://portal.librus.pl:443 "GET /api/v2/SynergiaAccounts/fresh/6379114u HTTP/1.1" 200 None
2019-10-02 11:54:58,240 - DEBUG - auth:67 - do_revalidation - 200 response {'id': 236268, 'group': 'student', 'accessToken': '4bBgvFbiwckyQfHUqbphm1yOO5BMTi7ysVM1IWIpI8sTo8Fr8OnYvZjQ8ley+QoL18ox6jOkG1m1j6Tkk4AK+mRR2CosNIKwuuzRZnRxkkovV4oKCfm2eSifz4Vc10P70UemrDCJS83d/YxX79/WDlj3R+r4NYV2/ss1PzdsGTnvmvtwUVykMXBIF39ou#j5PUMWW9gT8=', 'login': '6379114u', 'studentName': 'Krystian Postek', 'scopes': '', 'state': 'active'}
2019-10-02 11:54:58,241 - ERROR - poller:13 - exception_hook - Uncaught exception
Traceback (most recent call last):
  File "poller.py", line 26, in <module>
    logging.debug(session.grades_categorized)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 262, in grades_categorized
    for subject in self.subjects():
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 391, in subjects
    return self.return_objects('Subjects', cls=SynergiaSubject, extraction_key='Subjects')
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 231, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 177, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 122, in get
    response = self.dispatch_http_code(response, callback=self.get, callback_args=path, callback_kwargs=request_params)
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/core.py", line 87, in dispatch_http_code
    self.user.revalidate_user()
  File "/usr/local/lib/python3.7/dist-packages/librus_tricks/auth.py", line 71, in revalidate_user
    if new_token.json()['error'] == 'access_denied':
KeyError: 'error'
```

ugh, `0.7.6` w drodze

**Comment by barpec12** [comment]
Dostałem podobny błąd na 0.7.5
```
  File "main.py", line 183, in send_new_messages
    for news in session.news_feed():
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 383, in news_feed
    return self.return_objects('SchoolNotices', cls=SynergiaNews, extraction_key='SchoolNotices')
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 232, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 176, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 119, in get
    response = self.dispatch_http_code(response, callback=self.get, callback_args=path, callback_kwargs=request_params)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 84, in dispatch_http_code
    self.user.revalidate_user()
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/auth.py", line 73, in revalidate_user
    if new_token.json()['error'] == 'access_denied':
KeyError: 'error'

```

**Comment by Backdoorek** [comment]
Tia

**Comment by Backdoorek** [comment]
0.7.6 będzie poprawione

**Comment by barpec12** [comment]
Taki błąd dostałem na najnowszej wersji
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 218, in loop_in_thread
    loop.run_until_complete(send_new_messages())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "main.py", line 183, in send_new_messages
    for news in session.news_feed():
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 389, in news_feed
    return self.return_objects('SchoolNotices', cls=SynergiaNews, extraction_key='SchoolNotices')
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 237, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 183, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 127, in get
    callback_kwargs=request_params)
  File "/usr/local/lib/python3.7/site-packages/librus_tricks/core.py", line 104, in dispatch_http_code
    }[response.status_code]
KeyError: 503

```

**Comment by Backdoorek** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

![image](https://user-images.githubusercontent.com/30326322/66253070-0bf69a00-e763-11e9-96e2-6ae7272769ad.png)

**Comment by barpec12** [comment]
Rzeczywiście, zapomniałem o tym. Dzięki

**Comment by Backdoorek** [comment]
Wypuszczam dziś `0.7.6`. *No errors so far*
