### ISSUE TITLE
[BUG] Sala lekcyjna w jednostce lekcyjnej występuje jako klasa SynergiaTimetable

### ISSUE THREAD

**Issue by asdfMaciej** [Backdoorek/Librus-Tricks#16]
## Problem
Nie mogę uzyskać sali dla danej lekcji. W Librusie ustawione są poprawnie.

## Jak odtworzyć błąd
Odtwarzanie błędu krok po kroku:
```python3  
for l in session.today_timetable.lessons:
  print(l.classroom)
```

## Stacktrace
```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/librus_tricks/classes.py", line 813, in __str__
    for event in self.days[day_key]:
TypeError: 'SynergiaTimetableDay' object is not iterable
```

## Co powinno się stać
Powinna się wyświetlić sala lekcyjna [chyba]

## Zrzuty ekranu/debuggera
![](https://i.imgur.com/P4FnHqY.png)  

![](https://i.imgur.com/e76yX7V.png)

## Środowisko
  - OS: Ubuntu 16.04
  - Wersja pythona: 3.6.8

### Inne rzeczy
super projekt - w końcu porządny wrapper do API Librusa

**Comment by asdfMaciej** [comment]
```python3
>>> for l in session.today_timetable.lessons:
...     print(l.objects.return_id('classroom'))
...
3636
3636
3636
3625
3629
3619
3623
3623
>>>
```
IDy sal lekcyjnych istnieją, problem pojawia się przy:
```python3
>>> for l in session.today_timetable.lessons:
...     print(l.objects.assembly('classroom'))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/librus_tricks/classes.py", line 813, in __str__
    for event in self.days[day_key]:
TypeError: 'SynergiaTimetableDay' object is not iterable
```

**Comment by asdfMaciej** [comment]
I ręczne odtworzenie kodu z wnętrza naprawia sytuację:
```python3
>>> for l in session.today_timetable.lessons:
...     SynergiaClassroom.create(uid=l.objects.return_id('classroom'), session=l.objects._session)
...
<SynergiaClassroom 7>
<SynergiaClassroom 7>
<SynergiaClassroom 7>
<SynergiaClassroom 15>
<SynergiaClassroom 1SG>
<SynergiaClassroom 10>
<SynergiaClassroom 13>
<SynergiaClassroom 13>
```

**Comment by Backdoorek** [comment]
Próbowałem odtworzyć błąd, niestety wszystko działa jak należy. Czy mógłbyś mi zwrócić odpowiedzi api dal tych dwóch zapytań?
```py
session.get('Timetables')
session.get('Classrooms')
```

**Comment by asdfMaciej** [comment]
Jasne:
[timetables.txt](https://github.com/Backdoorek/Librus-Tricks/files/3711335/timetables.txt)
[classrooms.txt](https://github.com/Backdoorek/Librus-Tricks/files/3711336/classrooms.txt)
