### ISSUE TITLE
[HELP] Wyświetlanie ocen

### ISSUE THREAD

**Issue by timothyboman** [Backdoorek/Librus-Tricks#18]
## Problem
Postaraj się jak najdokładniej opisać problem

## Jak odtworzyć błąd
Odtwarzanie błędu krok po kroku:
1. Stwórz sesję s - `s = create_session(email, password)`
2. Wykonaj to `s.grades_categorized['Etyka']`
3. Otrzymasz coś takiego: `[<SynergiaGrade + from SynergiaSubject with id 36410 added 2019-09-30 21:15:37>]`
4. Wykonaj to `s.grades('36410')`
5. Zobacz error

## Stacktrace
```python
Traceback (most recent call last):
  File "<pyshell#65>", line 1, in <module>
    s.grades('36410')
  File "C:\Users\nazwa_uzytkownika\AppData\Local\Programs\Python\Python37-32\lib\site-packages\librus_tricks\core.py", line 265, in grades
    return self.return_objects('Grades', ids_computed, cls=SynergiaGrade, extraction_key='Grades')
  File "C:\Users\nazwa_uzytkownika\AppData\Local\Programs\Python\Python37-32\lib\site-packages\librus_tricks\core.py", line 239, in return_objects
    raw = self.get_cached_response(*path, max_lifetime=lifetime)
  File "C:\Users\nazwa_uzytkownika\AppData\Local\Programs\Python\Python37-32\lib\site-packages\librus_tricks\core.py", line 174, in get_cached_response
    http_response = self.get(*path, request_params=http_params)
  File "C:\Users\nazwa_uzytkownika\AppData\Local\Programs\Python\Python37-32\lib\site-packages\librus_tricks\core.py", line 129, in get
    callback_kwargs=request_params)
  File "C:\Users\nazwa_uzytkownika\AppData\Local\Programs\Python\Python37-32\lib\site-packages\librus_tricks\core.py", line 104, in dispatch_http_code
    }[response.status_code]
librus_tricks.exceptions.SynergiaAPIEndpointNotFound: https://api.librus.pl/2.0/Grades/3641036410
```

## Co powinno się stać
Wypisać ocenę, którą się dostało

## Środowisko
  - OS: Windows 10
  - Wersja pythona: 3.7.4

**Comment by Backdoorek** [comment]
Dziękuję za zgłoszenie tego błędu. Na obecną chwilę można użyć takiego rozwiązania
```py
s.grades('36410' + ',')
```
Za chwilę zrobię patcha.
