### ISSUE TITLE
Tworzenie wielu sesji kończy się niepowodzeniem

### ISSUE THREAD

**Issue by Backdoorek** [Backdoorek/Librus-Tricks#2]
Podczas ponownego tworzenia kolejnych sesji rzucany jest taki błąd.

```python
Traceback (most recent call last):
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python37\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\connection.py", line 183, in connect
    conn = self._new_conn()
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001626E1C7BC8>: Failed to establish a new connection: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Python Environments\librus_pwa\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /bar?code=def50200beb6476d3ff2ddfbaa55d5232f24e688ab07e73730256dbd87c73ed598f687dfe89d65cb15328bb8f3c6a847049544b1ba8b308e31b235b33d4b25b469b783fb416ce4632f050706de077ab4853f6e093c93fa31eb1ca6a766e52f6ff563ea13a1a2876fa0ce61a3d87c0ad7159d8640bbfc8ee3e394bcd940443af6c45bc2e619274ae8d00b604d43b7d4c6b624b129eb9f7e49616e5592a41af70ceb3bd5e4149fe7feb7143664cf09a5dadac04c2ad429c6713716825d5527c1189800a584df4a09f63e0644da2641ee33b36713a23b27002353727ef5b3df3a4173e9516c764145f5b22abceac285451245c96e145dcc9d399c3dc94a51b265d46d5f2e0b82f49153a3590d4b8a1832f01a5de692535c0f2ffc36e7573f50beb52dcb33e6b0cc24d5ca60976c0bc1d007000972342eb2e1c33529b863d7d3337035109e2cc1065e37495e8f76ccb7eff3dc362a2349d52b08120ecdefde2a7ad38b894ef70374c02f4343e3922cd87236b96d1a728c24e5c19982d09962eb25ac6f05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001626E1C7BC8>: Failed to establish a new connection: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python Environments\librus_pwa\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Python Environments\librus_pwa\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Python Environments\librus_pwa\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python Environments\librus_pwa\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Python Environments\librus_pwa\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python Environments\librus_pwa\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\PycharmProjects\librus_pwa\pwa_client\views.py", line 50, in post
    user = aio(email, password)
  File "D:\Python Environments\librus_pwa\lib\site-packages\librus_tricks\auth.py", line 175, in aio
    oauth_code = oauth_librus_code(email, passwd, revalidation=force_revalidation_method)
  File "D:\Python Environments\librus_pwa\lib\site-packages\librus_tricks\auth.py", line 64, in oauth_librus_code
    site = auth_session.get(LIBRUSLOGINURL)
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python Environments\librus_pwa\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /bar?code=def50mojtekoenniepatrz2349d52b08120ecdefde2a7ad38b894ef70374c02f4343e3922cd87236b96d1a728c24e5c19982d09962eb25ac6f05 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001626E1C7BC8>: Failed to establish a new connection: [WinError 10061] Nie można nawiązać połączenia, ponieważ komputer docelowy aktywnie go odmawia'))
```

**Comment by Backdoorek** [comment]
Rozwiązanie:
```python
try:
    user = aio(email, password, force_revalidation_method=True)
except:
    user = aio(email, password, force_revalidation_method=False) # Wykonywane tylko za pierwszym razem 
```
