### ISSUE TITLE
[BUG] timetable exception

### ISSUE THREAD

**Issue by lollul** [Backdoorek/Librus-Tricks#9]
## Jak odtworzyć błąd
from librus_tricks import SynergiaClient, authorizer
session = SynergiaClient(authorizer('xyz', 'xyz')[0], synergia_user_passwd='xyz')

timetable = session.today_timetable
print(*timetable)

## Stacktrace
```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/librus_tricks/classes.py", line 706, in __init__
    'classroom', resource['Classroom']['Id'], SynergiaTimetable
KeyError: 'Classroom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./librus-tricks.py", line 8, in <module>
    timetable = session.today_timetable
  File "/usr/lib/python3.7/site-packages/librus_tricks/core.py", line 332, in today_timetable
    return self.timetable().days[datetime.now().date()]
  File "/usr/lib/python3.7/site-packages/librus_tricks/core.py", line 320, in timetable
    return SynergiaTimetable.assembly(r['Timetable'], self)
  File "/usr/lib/python3.7/site-packages/librus_tricks/classes.py", line 761, in assembly
    self = cls(pseudo_id, resource, session)
  File "/usr/lib/python3.7/site-packages/librus_tricks/classes.py", line 747, in __init__
    self.parse_timetable(resource)
  File "/usr/lib/python3.7/site-packages/librus_tricks/classes.py", line 791, in convert_parsed_timetable
    timetable[day][event_index] = SynergiaTimetableEvent(timetable[day][event_index], self._session)
  File "/usr/lib/python3.7/site-packages/librus_tricks/classes.py", line 710, in __init__
    'classroom', resource['OrgClassroom']['Id'], SynergiaTimetable
KeyError: 'OrgClassroom'
```

## Środowisko
  - OS: (Arch)
  - Wersja pythona: (np. 3.7.4)

**Comment by Backdoorek** [comment]
Czy masz w planie lekcji, takie lekcje, które nie mają przydzielonej sali?

**Comment by lollul** [comment]
Chyba wszystkie lekcje są bez sali... Jaka szkoła, taki plan 😀

**Comment by Backdoorek** [comment]
Ok 15:00 spodziewaj się poprawki w update'cie `0.7.2`

**Comment by Backdoorek** [comment]
[Poprawiona wersja](https://pypi.org/project/librus-tricks/0.7.2/)

**Comment by lollul** [comment]
Dzięki, działa!

Tylko nie wiem co teraz bo:
````
    print(*timetable)
TypeError: print() argument after * must be an iterable, not SynergiaTimetableDay
````

**Comment by Backdoorek** [comment]
Z timetable zczytaj atrybut lessons `print(*timetable.lessons)
